#!/bin/bash

if [ ! -d "batfish" ]; then
	git clone https://github.com/batfish/batfish.git
	cd batfish
	if [ -f /etc/lsb-release ]; then		
		version=`lsb_release -rs`
		if [[ "$version" == '14.04' ]]; then
		   sudo tools/install_z3_ubuntu.sh /usr
		elif [[ "$version" == '16.04' ]]; then
		   sudo apt-get install gcc g++ make automake autoconf libtool
		   sudo tools/install_z3_ubuntu.sh /usr
		fi
	elif [ -f /etc/redhat-release ]; then
		sudo yum install gcc g++ make automake autoconf libtool
		sudo tools/install_z3_rhel_x86_64.sh /usr
	fi
	source tools/batfish_functions.sh
	batfish_build_all
else
	cd batfish
	source tools/batfish_functions.sh
fi

echo "Enter Full Path to Configs:"
read CONFIGS_PATH
CONFIGS_PATH+="/*" 
mkdir  -p Testrig/configs
cp  `grep -rnl "router bgp" $CONFIGS_PATH` Testrig/configs
allinone -cmdfile ../commands > ../allnodes.json
rm -rf Testrig
cd ..
mkdir BatfishJSONs
python single_json_generator.py
#git clone git@github.com:alanamramjit/config-scoring.git
python -c "import munkres" &> /dev/null
if [ $? -eq 1 ]; then
    sudo pip install munkres
fi
python -c "import Levenshtein" &> /dev/null
if [ $? -eq 1 ]; then
    sudo pip install python-Levenshtein
fi
python ip_matching.py BatfishJSONs/
rm -rf BatfishJSONs